FROM pytorch/pytorch

WORKDIR /workspace

#COPY ./Prediction /workspace
#COPY ./Model /workspace/Model
#COPY ./Utility /workspace/Utility
COPY ./Config/aws /root/.aws
#COPY ./requirements_pred.txt /workspace
COPY  . /workspace

RUN apt-get update
RUN apt-get install -y vim
RUN pip install -r requirements_pred.txt

WORKDIR /workspace/Prediction

CMD python app.py