FROM pytorch/pytorch

WORKDIR /workspace

#COPY ./Prediction /workspace
#COPY ./Model /workspace/Model
#COPY ./Utility /workspace/Utility
COPY ./Config/aws /root/.aws
COPY ./requirements_pred.txt /workspace